import React, { useState } from 'react';
import { DocumentAnalysisResult } from '../types';
import { X, Copy, Check, Download, Printer } from 'lucide-react';

interface ExportModalProps {
  analysis: DocumentAnalysisResult;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ analysis, onClose }) => {
  const [copied, setCopied] = useState(false);

  // Generate markdown brief
  const generateMarkdown = () => {
    return `# Legal Consultation Brief: ${analysis.documentType}
**Document Type:** ${analysis.documentType}  
**Total Risk Score:** ${analysis.totalRiskScore}/100 (${analysis.riskLevel.toUpperCase()})  
**Executive Verdict:** ${analysis.verdict}  
**Audit Timestamp:** ${new Date(analysis.analyzedAt).toLocaleDateString()}  
**Disclaimer:** Information only, not legal advice.

---

## 1. Executive Summary
${analysis.executiveSummary}

### Risk Pillar Subscores
- Financial Exposure: ${analysis.scoreBreakdown.financial}%
- Liability & Indemnity: ${analysis.scoreBreakdown.liability}%
- Termination Traps: ${analysis.scoreBreakdown.termination}%
- Ambiguity & Compliance: ${analysis.scoreBreakdown.compliance}%

---

## 2. Key Concerns & Verbatim Evidence (${analysis.keyConcerns.length} Items)

${analysis.keyConcerns.map((c, i) => `### § ${i + 1}. [${c.severity.toUpperCase()}] ${c.title}
- Clause Reference: ${c.clauseId}${c.clauseTitle ? ` (${c.clauseTitle})` : ''}
- Category: ${c.category}
- Verbatim Quote: "${c.verbatimQuote}"
- Hazard Analysis: ${c.impactAnalysis}
- Recommended Revision:
  > ${c.suggestedRevision}
`).join('\n')}

---

## 3. Missing Customary Protections (${analysis.missingClauses.length} Items)
${analysis.missingClauses.map(mc => `- **${mc.title}:** ${mc.description}\n  *Recommendation:* ${mc.standardProtection}`).join('\n')}

---

## 4. Eight Specific Questions to Ask a Lawyer
1. Does local housing law render the uncapped indemnification unenforceable as an unconscionable exculpatory clause?
2. Can the landlord legally accelerate 100% of remaining rent upon premature departure without a duty to mitigate damages?
3. Is the automatic renewal clause valid under local statutory notice requirements for commercial/residential leases?
4. Under what circumstances can the landlord withhold security deposit funds without an itemized repair estimate within 30 days?
5. Does the guest restriction clause violate statutory tenant rights to peaceful enjoyment of residential premises?
6. Are the late fees charged in Clause 2 considered unenforceable penalties rather than reasonable liquidated damages?
7. What addendum language would successfully cap tenant liability at the limit of tenant's commercial liability insurance?
8. If the property becomes partially uninhabitable due to landlord maintenance failures, does local statute permit rent withholding?

---
*Generated by Clause Court · Contract Sparring Partner*
`;
  };

  const mdContent = generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(mdContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${analysis.documentType.toLowerCase().replace(/\s+/g, '_')}_brief.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-[#141C2B]/60 flex items-center justify-center p-4">
      <div className="bg-[#EFE9DD] border border-[#141C2B] max-w-2xl w-full max-h-[85vh] flex flex-col">
        {/* Modal Header */}
        <div className="p-4 border-b border-[#141C2B]/16 bg-[#E5DED0] flex items-center justify-between">
          <div>
            <h3 className="font-serif text-lg font-normal text-[#141C2B] tracking-[-0.02em]">
              Legal Consultation Brief <span className="font-serif italic text-[#2C4A8F]">— Ready for Counsel</span>
            </h3>
            <p className="font-mono text-[10px] tracking-[0.08em] text-[#767E8C]">
              1-Page structured consultation markdown with cited clauses and 8 attorney questions.
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1 border border-[#141C2B]/16 text-[#767E8C] hover:text-[#141C2B] hover:bg-[#EFE9DD] cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Markdown Transcript Preview */}
        <div className="p-4 flex-1 overflow-y-auto bg-[#EFE9DD]">
          <pre className="font-mono text-[11px] leading-[1.9] tracking-[0.07em] text-[#141C2B] whitespace-pre-wrap p-4 bg-[#E5DED0] border border-[#141C2B]/16">
            {mdContent}
          </pre>
        </div>

        {/* Modal Action Bar */}
        <div className="p-4 border-t border-[#141C2B]/16 bg-[#E5DED0] flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 font-mono text-[11px] tracking-[0.08em] uppercase border border-[#141C2B] bg-[#EFE9DD] text-[#141C2B] hover:bg-[#141C2B] hover:text-[#EFE9DD] transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-[#2C4A8F]" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 font-mono text-[11px] tracking-[0.08em] uppercase border border-[#141C2B]/20 bg-[#EFE9DD] text-[#4A5364] hover:text-[#141C2B] transition-colors cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .md</span>
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 font-mono text-[11px] tracking-[0.08em] uppercase border border-[#141C2B]/20 bg-[#EFE9DD] text-[#4A5364] hover:text-[#141C2B] transition-colors cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Brief</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="px-4 py-1.5 font-mono text-[11px] tracking-[0.08em] uppercase border border-[#141C2B]/20 bg-[#EFE9DD] text-[#767E8C] hover:text-[#141C2B] cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
